import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Hello World App",
  description: "Generated by create-next-app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://demo-styles.deno.deno.net/styles.css"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
